### ISSUE TITLE
missing allele KIR2DP1*014

### ISSUE THREAD

**Issue by sklas** [ANHIG/IPDKIR#25]
Hi,

allele KIR2DP1\*014 seems missing in the KIR.dat of release 2.8.0.
It is not mentioned in the Deleted_alleles.txt, but can be found in the Allelelist.280.txt.
So I guess it should be there and is not removed on purpose.

Thanks,
Steffen

**Comment by jrob119** [comment]
As detailed at https://www.ebi.ac.uk/ipd/kir/docs/version_280.html, this allele is temporarily held while the naming is under review (Nov-2018).
