### ISSUE TITLE
Spurious newline in KIR.dat

### ISSUE THREAD

**Issue by gschofl** [ANHIG/IPDKIR#32]
A spurious newline character has made it into KIR.dat at lines 138574 and 184931

![image](https://user-images.githubusercontent.com/988635/73268737-cc553180-41db-11ea-94a5-501939a389fb.png)

Cheers,
Gerhard

**Comment by jrob119** [comment]
The file has been updated, thanks for reporting this issue.

**Comment by sklas** [comment]
Hi,
This issue has also made it into the current release.
![image](https://user-images.githubusercontent.com/3309194/104922250-bddac980-599a-11eb-883b-0a01f01c108f.png)
Best,
Steffen
