### ISSUE TITLE
Newline character in KIR.dat

### ISSUE THREAD

**Issue by sklas** [ANHIG/IPDKIR#35]
Hi,
a wrong newline character can be found in the KIR.dat of the current release, similar to issue #32 .

![image](https://user-images.githubusercontent.com/3309194/107611249-dd84ab00-6c43-11eb-8e9a-9aaa61afbc99.png)

Best,
Steffen

**Comment by dominicbarkerAN** [comment]
Hi Steffen,

Thank you for bringing this issue to our attention in the latest release. An updated version of this file is now avaiable on branch 2100 and Latest.

Best,

Dominic
