### ISSUE TITLE
Missing Exon 5 in genes with combined intron 3/4

### ISSUE THREAD

**Issue by sklas** [ANHIG/IPDKIR#44]
Hi, 
there is a problem with the gene feature annotation in genes with a combined intron 3 and 4.
Exon 5 is missing in the annotation and the part of the sequence that used to be exon 5 is added to intron 3/4.

2.10.0:
![Image20220105090735](https://user-images.githubusercontent.com/3309194/148182468-02c48f56-3535-4f8e-a2f2-fd0fb957ca31.png)
2.11.0:
![image](https://user-images.githubusercontent.com/3309194/148182614-2c115356-8bd1-4cbd-9f27-be09565a7dbe.png)

Best,
Steffen

**Comment by bmschoene** [comment]
@dominicbarkerAN, @jrob119  Can you guys please look into & fix this?

Until it is fixed:
- All our genotyping results are still KIR2.10 based.
- We cannot let TypeLoader use KIR 2.11 until it is fixed. So all novel KIR files you are currently getting that are created by TypeLoader are still KIR2.10 based.

**Comment by dominicbarkerAN** [comment]
Hello, thank you for bringing this issue to our attention. This is now corrected in the 2.12.0 release of the IPD-KIR database on the 2120 and Latest branch. We will look to also make this correction in previous versions.
