### ISSUE TITLE
kir.dat not updated in 2.12.0

### ISSUE THREAD

**Issue by bmschoene** [ANHIG/IPDKIR#49]
The new release does not seem to have changed the `kir.dat` file?
![image](https://user-images.githubusercontent.com/43027482/208093217-86959e43-9fb9-43c4-b670-8d80dd000ffc.png)

(Neither was `Readme.md` updated, but that hurts us less. ^^)

**Comment by dominicbarkerAN** [comment]
Hi Bianca, thank you for pointing out this oversight. An updated version has now been included in the 2120 and Latest branch.
