### ISSUE TITLE
Renaming of KIR.dat to kir.dat

### ISSUE THREAD

**Issue by bmschoene** [ANHIG/IPDKIR#51]
Hi,

we noticed that in the 2.12.0 release, you have renamed the `KIR.dat` file to `kir.dat`.
This now makes the spelling consistent with `hla.dat`, but it's different from what our software was expecting based on past releases.

So my question is: is this a deliberate, permanent change (so we'll adjust our software to expect the lowercase spelling in the future)
Or was it just by chance and will change back?

Best regards,
Bianca

**Comment by dominicbarkerAN** [comment]
Hi Bianca,

This is indeed a deliberate change to bring the format of the KIR files more in line with HLA.
