### ISSUE TITLE
Sequence length not matching feature annotation for KIR2DL5A*00102

### ISSUE THREAD

**Issue by sklas** [ANHIG/IPDKIR#53]
Hi,

in release 2.13.0 several partial introns have been added to KIR2D5A*00102 without changing the sequence.
In 2.12.0 there was only Intron 1 annotated and the length of features did match the provided sequence.
Now, the feature annotation ends at position 9,486 while the sequence is only 2,350 base long.

Best,
Steffen

2.12.0:
![image](https://github.com/ANHIG/IPDKIR/assets/3309194/88f71bfc-aab8-4844-aa87-5b508cb697ae)
2.13.0
![image](https://github.com/ANHIG/IPDKIR/assets/3309194/f6b4eb7f-280b-426a-8edd-b2370d68e834)

**Comment by dominicbarkerAN** [comment]
Hi Steffen, thank you for bringing this issue to our attention. Currently we are preparing the release of the HLA database and then we will look at this error next week.

Best,

Dominic

**Comment by dominicbarkerAN** [comment]
Hi Steffen,

I apologise for this issue not being resolved earlier, however we have now completed the 2.14.0 release of the IPD-KIR database and through this process have resolved this issue. I have also updated the 2.13.0 branch to reflect the correction.

Best,

Dominic
