### ISSUE TITLE
KIR file kir_nuc.fasta has duplicate sequences

### ISSUE THREAD

**Issue by colinhercus** [ANHIG/IPDKIR#54]
Hi,

Following sequences are duplicated in the NUC fasta file

grep "^>" kir_nuc.fasta | uniq -c | grep " 2 "
      2 >KIR:KIR00536 KIR2DL5A*014 1128 bp
      2 >KIR:KIR00537 KIR2DL5A*015 1128 bp
      2 >KIR:KIR00907 KIR2DL5A*022 1128 bp
      2 >KIR:KIR00993 KIR2DL5A*024 1128 bp
      2 >KIR:KIR01191 KIR2DL5A*025 1128 bp
      2 >KIR:KIR01194 KIR2DL5A*026 1128 bp
      2 >KIR:KIR01195 KIR2DL5A*027 1128 bp
      2 >KIR:KIR01202 KIR2DL5A*028 1128 bp
      2 >KIR:KIR01210 KIR2DL5A*029 1128 bp
      2 >KIR:KIR01213 KIR2DL5A*030 1128 bp
      2 >KIR:KIR01220 KIR2DL5A*031 1128 bp
      2 >KIR:KIR01223 KIR2DL5A*032N 1128 bp
      2 >KIR:KIR01588 KIR2DL5A*040 1128 bp
      2 >KIR:KIR01687 KIR2DL5A*042 1128 bp
      2 >KIR:KIR00259 KIR2DL5A*00102 1128 bp
      2 >KIR:KIR00260 KIR2DL5A*00103 1128 bp
      2 >KIR:KIR00262 KIR2DL5A*00104 1128 bp
      2 >KIR:KIR00263 KIR2DL5A*00105 1128 bp
      2 >KIR:KIR01201 KIR2DL5A*00106 1128 bp
      2 >KIR:KIR01214 KIR2DL5A*00107 1128 bp
      2 >KIR:KIR01218 KIR2DL5A*00108 1128 bp
      2 >KIR:KIR00391 KIR2DL5A*01201 1128 bp
      2 >KIR:KIR00389 KIR2DL5A*01202 1128 bp
      2 >KIR:KIR00029 KIR2DL5A*0010101 1128 bp
      2 >KIR:KIR00300 KIR2DL5A*0010102 1128 bp
      2 >KIR:KIR00439 KIR2DL5A*0010103 1128 bp
      2 >KIR:KIR01039 KIR2DL5A*0010104 1128 bp
      2 >KIR:KIR01041 KIR2DL5A*0010105 1128 bp
      2 >KIR:KIR01217 KIR2DL5A*0010106 1128 bp
      2 >KIR:KIR01196 KIR2DL5A*0010901 1128 bp
      2 >KIR:KIR01219 KIR2DL5A*0010902 1128 bp
      2 >KIR:KIR00095 KIR2DL5A*0050101 1128 bp
      2 >KIR:KIR00249 KIR2DL5A*0050102 1128 bp
      2 >KIR:KIR00438 KIR2DL5A*0050103 1128 bp
      2 >KIR:KIR00440 KIR2DL5A*0050104 1128 bp
      2 >KIR:KIR01209 KIR2DL5A*0050105 1128 bp
      2 >KIR:KIR00882 KIR2DL5A*0210101 1128 bp
      2 >KIR:KIR01221 KIR2DL5A*0210102 1128 bp
      2 >KIR:KIR01222 KIR2DL5A*0210103 1128 bp
      2 >KIR:KIR00992 KIR2DL5A*0230101 1128 bp
      2 >KIR:KIR01199 KIR2DL5A*0230102 1128 bp
      2 >KIR:KIR01200 KIR2DL5A*0330101 1128 bp
      2 >KIR:KIR01212 KIR2DL5A*0330102 1128 bp
      2 >KIR:KIR01215 KIR2DL5A*0340101 1128 bp
      2 >KIR:KIR01216 KIR2DL5A*0340102 1128 bp
      2 >KIR:KIR00031 KIR2DL5B*003 1128 bp
      2 >KIR:KIR00032 KIR2DL5B*004 1128 bp
      2 >KIR:KIR00245 KIR2DL5B*009 1128 bp
      2 >KIR:KIR00264 KIR2DL5B*010 1128 bp
      2 >KIR:KIR00265 KIR2DL5B*011 1128 bp
      2 >KIR:KIR00538 KIR2DL5B*016 1128 bp
      2 >KIR:KIR00664 KIR2DL5B*017 1128 bp
      2 >KIR:KIR00684 KIR2DL5B*018 1128 bp
      2 >KIR:KIR00803 KIR2DL5B*019 1128 bp
      2 >KIR:KIR00804 KIR2DL5B*020 1128 bp
      2 >KIR:KIR01205 KIR2DL5B*035 1128 bp
      2 >KIR:KIR01206 KIR2DL5B*036 1128 bp
      2 >KIR:KIR01208 KIR2DL5B*037 1128 bp
      2 >KIR:KIR01190 KIR2DL5B*038 1128 bp
      2 >KIR:KIR01596 KIR2DL5B*041 1128 bp
      2 >KIR:KIR00802 KIR2DL5B*00203 1128 bp
      2 >KIR:KIR00994 KIR2DL5B*00204 1128 bp
      2 >KIR:KIR01193 KIR2DL5B*00205 1128 bp
      2 >KIR:KIR00125 KIR2DL5B*00601 1128 bp
      2 >KIR:KIR00267 KIR2DL5B*00602 1128 bp
      2 >KIR:KIR00393 KIR2DL5B*00603 1128 bp
      2 >KIR:KIR00266 KIR2DL5B*00802 1128 bp
      2 >KIR:KIR00682 KIR2DL5B*00803 1128 bp
      2 >KIR:KIR00805 KIR2DL5B*00804 1128 bp
      2 >KIR:KIR00946 KIR2DL5B*00805 1128 bp
      2 >KIR:KIR00390 KIR2DL5B*01301 1128 bp
      2 >KIR:KIR00392 KIR2DL5B*01302 1128 bp
      2 >KIR:KIR00534 KIR2DL5B*01303 1128 bp
      2 >KIR:KIR00801 KIR2DL5B*01304 1128 bp
      2 >KIR:KIR00030 KIR2DL5B*0020101 1128 bp
      2 >KIR:KIR00248 KIR2DL5B*0020102 1128 bp
      2 >KIR:KIR00301 KIR2DL5B*0020103 1128 bp
      2 >KIR:KIR00394 KIR2DL5B*0020104 1128 bp
      2 >KIR:KIR00524 KIR2DL5B*0020106 1128 bp
      2 >KIR:KIR00632 KIR2DL5B*0020107 1128 bp
      2 >KIR:KIR01095 KIR2DL5B*0020108 1128 bp
      2 >KIR:KIR01197 KIR2DL5B*0020109 1128 bp
      2 >KIR:KIR01198 KIR2DL5B*0020110 1128 bp
      2 >KIR:KIR01204 KIR2DL5B*0020111 1128 bp
      2 >KIR:KIR00535 KIR2DL5B*0020201 1128 bp
      2 >KIR:KIR00972 KIR2DL5B*0020202 1128 bp
      2 >KIR:KIR00126 KIR2DL5B*0070101 1128 bp
      2 >KIR:KIR00525 KIR2DL5B*0070102 1128 bp
      2 >KIR:KIR00244 KIR2DL5B*0080101 1128 bp
      2 >KIR:KIR00395 KIR2DL5B*0080102 1128 bp
      2 >KIR:KIR01207 KIR2DL5B*0390101 1128 bp
      2 >KIR:KIR01203 KIR2DL5B*0390102 1128 bp

Colin

**Comment by dominicbarkerAN** [comment]
Thank you for bringing this issue to our attention, this has now been updated in the Latest and 2130 branch
